version: "3"
services:
  go:
    container_name: Database_And_Exercises_GO
    build:
      context: ./Docker/go
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    env_file:
      - ./Docker/go/.env
    volumes:
      - ./go:/go/src/app
    ports:
      - 443:8080
    depends_on:
      - "mysql"

  mysql:
    container_name: Database_And_Exercises_DB
    build:
      context: ./Docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./Docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      # MYSQL_USER: yuramaru
      # MYSQL_PASSWORD: yuramaru_pass
