FROM python:3.10
USER root

RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

RUN apt-get install -y vim less
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN python -m pip install sqlmodel
RUN python -m pip install load-dotenv
RUN python -m pip install mysql-connector-python
RUN python -m pip install fastapi
RUN python -m pip install uvicorn
RUN python -m pip install cerberus

# CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]